name: test for plus

on:
  push:
    paths:
      - "plus"
      
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
      - uses: actions/checout@v3
  
      

      - name: make plus executable
        run: chmod +x plus

      - name: run test
        run: bash -xv ./plus
