name: test for plus

on:
  push:
    paths:
      - "plus"
      - ".github/workflows/plus.yml"
  pull_request:

jobs:
  test:
    run-on: ubuntu-latest
    
    steps:
      - name: checkout code
      - usues: actions/checout@v3
  
      

      - name: make plus executable
        run: chmod +x plus

      - name: run test
        run: bash -xv ./test.bash
